# Generated by Django 4.1.3 on 2022-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200419_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=65403, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Others', 'Others')], max_length=45),
        ),
    ]
